{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PLOTLY DASH - ACIDENTES RODOVIARIOS"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Lib's"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:02:46.138768Z",
     "start_time": "2022-05-18T13:02:43.221227Z"
    }
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import re\n",
    "import os\n",
    "\n",
    "from dash import Dash\n",
    "import dash_bootstrap_components as dbc\n",
    "from dash.dependencies import Input, Output\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "\n",
    "import plotly.express as px\n",
    "import base64\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:02:59.826862Z",
     "start_time": "2022-05-18T13:02:47.238825Z"
    }
   },
   "outputs": [],
   "source": [
    "#reading data\n",
    "path = 'data'\n",
    "lista = []\n",
    "df = pd.DataFrame()\n",
    "\n",
    "for f in os.listdir(path + \"/\"):\n",
    "    frames = pd.read_csv(path + \"/\" + f, encoding = 'latin-1', sep = ';', low_memory = False)\n",
    "    file = re.search(r'\\d+', f).group(0)\n",
    "    \n",
    "    frames['file'] = file\n",
    "    df = df.append(frames, ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:00.227299Z",
     "start_time": "2022-05-18T13:02:59.829951Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2007-01-01 00:00:00\n",
      "2021-06-30 00:00:00\n"
     ]
    }
   ],
   "source": [
    "# data type\n",
    "df['data_inversa'] = df['data_inversa'].astype('datetime64')\n",
    "\n",
    "print(df['data_inversa'].min())\n",
    "print(df['data_inversa'].max())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:01.489645Z",
     "start_time": "2022-05-18T13:03:00.230405Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "00:00:00 23:59:00\n"
     ]
    }
   ],
   "source": [
    "# add new columns\n",
    "df['month'] = df['data_inversa'].dt.month\n",
    "df['year'] = df['data_inversa'].dt.year\n",
    "\n",
    "df['time'] = df['horario'].str.slice(0, 2)\n",
    "\n",
    "print(df['horario'].min(), df['horario'].max())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:02.829404Z",
     "start_time": "2022-05-18T13:03:01.494872Z"
    }
   },
   "outputs": [],
   "source": [
    "# getting only the target columns\n",
    "df1 = df[['dia_semana', 'uf', 'br', 'km',\n",
    "       'municipio', 'causa_acidente', 'tipo_acidente',\n",
    "        'fase_dia', \n",
    "       'condicao_metereologica', 'tipo_pista', \n",
    "       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',\n",
    "       'ignorados', 'feridos', 'file', 'month', 'year', 'time']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:06.678292Z",
     "start_time": "2022-05-18T13:03:02.831640Z"
    }
   },
   "outputs": [],
   "source": [
    "#replacing some values\n",
    "df1 = df1.copy(deep = True)\n",
    "\n",
    "df1['dia_semana'] = [x.lower() for x in df1['dia_semana']]\n",
    "df1['dia_semana'] = [x.replace('-feira', '') for x in df1['dia_semana']]\n",
    "\n",
    "df1['causa_acidente'] = df1['causa_acidente'].str.lower()\n",
    "\n",
    "dict_replace = {'ingestão de álcool e/ou substâncias psicoativas pelo pedestre' : 'ingestão de álcool',\n",
    "               'ingestão de álcool ou de substâncias psicoativas pelo pedestre' : 'ingestão de álcool',\n",
    "               'ingestão de álcool pelo condutor' : 'ingestão de álcool',\n",
    "               'redutor de velocidade em desacordo' : 'velocidade incompatível',\n",
    "               'dormindo' : 'condutor dormindo',\n",
    "               'falta de atenção à condução' : 'falta de atenção',\n",
    "               'defeito mecânico em veículo' : 'defeito mecânico no veículo',\n",
    "               'mal súbito do condutor' : 'mal súbito'}\n",
    "\n",
    "df1 = df1.replace({'causa_acidente' : dict_replace})\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PLOTLY DASHBOARD"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:07.091575Z",
     "start_time": "2022-05-18T13:03:06.681550Z"
    }
   },
   "outputs": [],
   "source": [
    "df = df1.copy(deep = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:03:09.516738Z",
     "start_time": "2022-05-18T13:03:07.093537Z"
    }
   },
   "outputs": [],
   "source": [
    "df = df[df['uf'] != '(null)']\n",
    "df = df.dropna()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "start_time": "2022-05-18T13:35:56.456Z"
    },
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"\u001b[36mGET /assets/01-style.css?m=1652832404.0301301 HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_favicon.ico?v=2.0.0 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:35:58] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [18/May/2022 10:35:58] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/wv/w46jcg9n1wg9gv31ph4v6nvr0000gn/T/ipykernel_1189/2802067981.py\", line 76, in update_line_plot\n",
      "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 1538, in __getitem__\n",
      "    return super().__getitem__(key)\n",
      "  File \"/Users/daianeklein/miniconda3/envs/venv-dash/lib/python3.9/site-packages/pandas/core/base.py\", line 227, in __getitem__\n",
      "    raise KeyError(f\"Column not found: {key}\")\n",
      "KeyError: 'Column not found: None'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [18/May/2022 10:36:02] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [18/May/2022 10:36:03] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/May/2022 10:36:03] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY],\n",
    "                meta_tags = [{'name' : 'viewport',\n",
    "                              'content' : 'width=dice_width, initial-scale=1.0'}])\n",
    "\n",
    "\n",
    "app.layout = dbc.Container([\n",
    "    html.P(' '),\n",
    "    html.Div(id = 'first-line-separator'),   \n",
    "    html.Div([\n",
    "            html.H2('ACIDENTES RODOVIÁRIOS', className = 'text-general'),\n",
    "            html.H5('2008 à 2021',  className = 'text-general')\n",
    "            ], className = 'div-config'),\n",
    "                    \n",
    "    html.Div([\n",
    "        html.P('Dashboard referente a acidentes rodoviários registrados no período de 2008 à 2021 disponibilizados pela Polícia Federal do Brasil',\n",
    "              id = 'dashboard-sub-title'),\n",
    "        ],\n",
    "   ), \n",
    "    html.Div(id = 'second-line-separator', style = {'border' : '2px #343a40 solid',\n",
    "                                                   'margin-bottom' : '10px'}),\n",
    "    \n",
    "    #filter section\n",
    "    html.Div([\n",
    "        dbc.Row([\n",
    "            dbc.Col([\n",
    "                html.H3('Ano da Ocorrência', className = 'text-filter'),\n",
    "                dcc.RangeSlider(\n",
    "                                min=2011,\n",
    "    max=2021,\n",
    "    step=1,\n",
    "    marks = {str(i) : i for i in df['year'].unique()},\n",
    "    value=[i for i in sorted(df['year'].unique())],\n",
    "                                id='selected_year_slider',\n",
    "                               className = 'year-slider')],\n",
    "                width = {'size' : 6}),\n",
    "            \n",
    "            dbc.Col([\n",
    "                html.H3('UF da Ocorrência', className = 'text-filter'),\n",
    "                dcc.Dropdown(id='dropdown-uf',\n",
    "                            multi = False,\n",
    "                             options = [{'label' : x, 'value' : x} for x in sorted(df['uf'].unique())],\n",
    "                             className = 'dropdown-states')],\n",
    "            width = {'size' : 2}, className = 'cols-filters'),\n",
    "            \n",
    "            dbc.Col([\n",
    "                html.H3('Vítimas', className = 'text-filter'),\n",
    "                dcc.Checklist(id='vitimas-selected',\n",
    "                             options = [{'label' : 'Total', 'value': 'total'},\n",
    "                                     {'label' : 'Ilesos', 'value' : 'ilesos'},\n",
    "                                     {'label' : 'Feridos', 'value' : 'feridos'},\n",
    "                                     {'label' : 'Mortos', 'value' : 'mortos'},\n",
    "                                    ], className = 'vitimas-col', inputStyle={\"margin-right\": \"20px\"})\n",
    "            ], width = {'size' : 4}, className = 'vitimas-selected')\n",
    "        ])\n",
    "    ], className = 'div-config'),\n",
    "    \n",
    "    html.Div([\n",
    "        dbc.Row([\n",
    "            dbc.Col([\n",
    "                dcc.Graph(id='lineplot', figure = {},\n",
    "                        )\n",
    "            ])\n",
    "        ])\n",
    "    ])\n",
    "      \n",
    "])\n",
    "\n",
    "\n",
    "@app.callback(\n",
    "    Output('lineplot', 'figure'),\n",
    "    [Input('selected_year_slider', 'value'),\n",
    "    Input('dropdown-uf', 'value'),\n",
    "    Input('vitimas-selected', 'value')])\n",
    "def update_line_plot(selected_year_slider, uf_selected, vitimas):\n",
    "    aux = df[(df['year'].isin(selected_year_slider)) & (df['uf'].isin([uf_selected]))]\n",
    "    aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
    "    \n",
    "    fig = px.line(aux, x = 'year', y = vitimas, height = 300)\n",
    "    fig.update_layout({\n",
    "        'plot_bgcolor' : '#2f3031',\n",
    "         'paper_bgcolor': '#2f3031'},\n",
    "    margin = dict(l=20, r=20, t=20, b=20))\n",
    "    fig.update_xaxes(type='category',\n",
    "                    showgrid = False,\n",
    "                     showline= True,\n",
    "                     title_text = 'Year',\n",
    "                     color='#c8c9ca',\n",
    "                     title_font = {'size' : 10},\n",
    "                    tickfont=dict(color='#c8c9ca',\n",
    "                                 size = 8))\n",
    "    \n",
    "    fig.update_yaxes(showgrid = False,\n",
    "                     showticklabels = True,\n",
    "                     title = None,\n",
    "                     showline= True,\n",
    "                     title_text = 'Quantidade',\n",
    "                     color='#c8c9ca',\n",
    "                     title_font = {'size' : 10},\n",
    "                    tickfont=dict(color='#c8c9ca',\n",
    "                                 size = 8))\n",
    "    \n",
    "    fig.update_traces(line_color = '#c8c9ca',\n",
    "                      line_width=1.5,\n",
    "                     textfont_size=6.5,\n",
    "                     textposition='top center',\n",
    "                    textfont_color = 'grey')\n",
    "\n",
    "    return fig\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()\n",
    "    \n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2022-05-18T13:31:42.832922Z",
     "start_time": "2022-05-18T13:31:42.712443Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>feridos</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2011</td>\n",
       "      <td>12690</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2012</td>\n",
       "      <td>12445</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   year  feridos\n",
       "0  2011    12690\n",
       "1  2012    12445"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "selected_year_slider = [2011,2012]\n",
    "uf_selected = ['SP', 'RJ']\n",
    "vitimas = 'feridos'\n",
    "\n",
    "aux = df[(df['year'].isin(selected_year_slider)) & (df['uf'].isin(uf_selected))]\n",
    "#aux = aux[]\n",
    "aux = aux.groupby('year', as_index = False)[vitimas].sum()\n",
    "\n",
    "aux"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv-dash",
   "language": "python",
   "name": "venv-dash"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
